version: "3.9"
services:
  web:
    build: .
    environment:
      ENV: development
    ports:
      - "4000:4000"
    command: ["cargo", "run"]
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

